### ISSUE TITLE
Use OOP-based language bindings/wrappers

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rgb-sdk#29] opened 2020-12-05 17:37 UTC
Noticed very strange pattern used in NodeJS, and expect that it may be the case for other languages.

```javascript
    await rgbNode.startRgb(
        config.network, config.stash_endpoint, config.contract_endpoints, config.threaded, config.datadir)
    .then(r => {
        console.log("RGB node runtime has started")
        runtime = r
    })
    .then(assets => {
        // consignment = fs.readFileSync(consignmentPath)
        return rgbNode.validate(runtime, consignmentPath)
    })
```

while in OOP world we should have an object exposing RGB node methods, so
```javascript
let rgb = rgbNode.startRgb(...);
rgb.validate(consignmentPath);
// ...
```

**Comment by zoedberg** [comment] 2020-12-07 09:50
I don't understand what's the purpose of this issue. IMO we already have #24 for this: improvement of parameters will require adding wrappers, as decided there

> Noticed very strange pattern used in NodeJS, and expect that it may be the case for other languages.

that's not strange at all, node.js is based on the concept of `Promise`s (more info [here](https://nodejs.dev/learn/understanding-javascript-promises)), so this pattern is very common to see in that world.
since `Promise`s are used to handle async operations, I think that it's correct and expected that calls to rgb methods will return them. but this is not the case for other languages

> while in OOP world we should have an object exposing RGB node methods, so

js (and node.js) are OOP too. looking at a [list of OOP languages](https://en.wikipedia.org/wiki/List_of_object-oriented_programming_languages) I can see several languages that don't strictly follow your example. I think we cannot generalize so much, we'll need to decide language by language which is the best structure/pattern to use

**Comment by dr-orlovsky** [comment] 2020-12-07 11:25
I know what promises are; my comment was not about them first of all. It was about encapsulation. 

Since you mentioned promises, I will also point out they are not used for sync/blocking calls since they are blocked anyway. It creates a sense of ascynchronicity where no asynchronicity is present.

**Comment by zoedberg** [comment] 2020-12-07 15:05
> I know what promises are; my comment was not about them first of all. It was about encapsulation.

from the issue description I deduced that you were referring to the `Promise`s chain, since you talked about "strange pattern" and not about encapsulation.

this piece of code could have been done in several ways, but being this a demo I don't think we should worry about its structure (which is related to node.js and not to the sdk), users integrating rgb via the node.js bindings will surely have/need a different structure. the important thing is that each rgb method will return a `Promise` (rejected or resolved, this is handled by swig interface)

we can also achieve something similar to:
```
let rgb = rgbNode.startRgb(...);
rgb.validate(consignmentPath);
```
by using the wrapper we're planning to add to hide the runtime object (same as it's already being done for java), but this won't change demo's structure, since the chain of `Promise`s will still be the quicker way to perform a sequence of calls, and won't add extra functionality (just an aesthetic matter)

I still believe this is a duplicate of #24, since we will need to introduce language-specific wrappers to solve that issue. Am I wrong? (if so please clarify what you meant)

**Comment by dr-orlovsky** [comment] 2020-12-07 16:47
Promises are not looking "strange" to me at all; what is looking strange is the fact that having an object already (`runtime`) we just do not call methods on it. As for the promises, I already expressed my opinion that w/o asynchronicity they are not needed and create more problems than benefits.

**Comment by dr-orlovsky** [comment] 2020-12-07 16:52
And this is not duplicate of #24 since that issue is about parameter data types

**Comment by zoedberg** [comment] 2020-12-07 18:30
> what is looking strange is the fact that having an object already (runtime) we just do not call methods on it

all sdk methods (besides `start_rgb`/`run_rgb_embedded`) require runtime as a parameter. so to allow users to call methods on it, we need to add a wrapper (that will just hide this detail), which is the purpose of this issue. so I don't understand why you found strange that "pattern" (and that's why I thought you were referring to the `Promise`s chain)

> As for the promises, I already expressed my opinion that w/o asynchronicity they are not needed and create more problems than benefits.

I didn't understand this from your previous message. so you're saying we should remove them?
if so, I don't agree. since most of rgb operations will require network/db access (or other long operations), it feels normal to run them as async methods. in the node.js world, all libraries have changed (or are changing) their methods in order to return `Promise`s.
I'm not a fan of `Promise`s, but they don't cause problems (besides headaches or illegibility), that's how node.js works and what developers will expect to receive

**Comment by dr-orlovsky** [comment] 2020-12-09 18:54
1. I do not see why all these methods https://github.com/LNP-BP/rgb-sdk/blob/master/ffi/nodejs/rgb_node.js#L11-L38 can't be just a methods on JS object which will be exported and maintain runtime internally. That what I meant by the issue

2. Network requests in RGB Node are all synchroneous (b/c of ZMQ setup) and this can't be simply changed w/o deep refactoring of the node itself (LNP is async for instance). So having promises here is misleading and useless.

**Closed as completed** 2020-12-17 13:48 UTC
Labels: enhancement, good first issue
