### ISSUE TITLE
docker post-build stuff failed on debian

### ISSUE THREAD

**Issue by alexeyneu** [LNP-BP/rgb-sdk#53] opened 2021-01-28 22:52 UTC
parrot-linux really

![Screenshot_2021-01-29_01-40-28](https://user-images.githubusercontent.com/31589671/106208598-ab4f6400-61d4-11eb-84cd-3220fd0a9818.png)
  
```bash
docker build -f bindings/android/Dockerfile -t rgb-sdk-android .
mkdir -p artifacts/android
docker run --rm -v $(pwd):/opt/mount --entrypoint bash \
    rgb-sdk-android \
    -c 'cp /rgb-sdk/bindings/android/library/build/outputs/aar/*.aar /opt/mount/artifacts/android/'
```
and this is fail of the last one. this was stated as a build reference or so

**Comment by alexeyneu** [comment] 2021-01-31 16:16
it's been compiled finally. stuff here happened because first time compilation script was hanged on final stage , after `successful build`

**Comment by dr-orlovsky** [comment] 2021-01-31 18:37
I assume the issue can be closed?

**Comment by UkolovaOlga** [comment] 2021-01-31 19:18
The issue is closed as the author reported its being outdated

**Closed as completed by UkolovaOlga** 2021-01-31 19:18 UTC
Labels: invalid, question
